[build]
    command = "npm run build"
    functions = "heropy"
    publish = "dist"

[dev]
    framework = "#custom"
    command= "npm run dev"
    targetPort = 8080
    port = 8888
    publish = "dist"
    autoLaunch = false